# Generated by Django 4.2.3 on 2023-08-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_year', models.PositiveIntegerField()),
                ('site_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
