# Generated by Django 4.2.3 on 2023-08-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_faicon_footerlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterLinks',
            new_name='FooterLink',
        ),
    ]
