# Generated by Django 4.2.3 on 2023-08-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_blog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='body',
        ),
    ]
